name: Enforce Branch Naming Convention

on:
  create:
    branches: # Trigger when a new branch is pushed

jobs:
  check-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch name
        run: |
          BRANCH_NAME="${{ github.ref }}"
          echo "Branch name: $BRANCH_NAME"

          if [[ ! "$BRANCH_NAME" =~ ^refs/heads/(feature|release)/ ]]; then
            echo "❌ ERROR: Branch name must start with 'feature/' or 'release/'."
            exit 1
          fi

          echo "✅ Branch name is valid."
