name: CI/CD Pipeline

on:
  push:
    branches:
      - main

env:
  REGISTRY: docker.io
  IMAGE_BACKEND: docker.io/${{ secrets.DOCKER_USERNAME }}/spring-boot-app
  IMAGE_FRONTEND: docker.io/${{ secrets.DOCKER_USERNAME }}/vue-app

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build and Test Backend
        working-directory: backend
        run: |
          ./mvnw clean install
          ./mvnw test

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Build and Test Frontend
        working-directory: frontend
        run: |
          npm install
          npm run build

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Backend Docker Image
        run: |
          docker build -t $IMAGE_BACKEND:latest -f backend/Dockerfile backend/
          docker push $IMAGE_BACKEND:latest

      - name: Build and Push Frontend Docker Image
        run: |
          docker build -t $IMAGE_FRONTEND:latest -f frontend/Dockerfile frontend/
          docker push $IMAGE_FRONTEND:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Update Kubernetes Manifests
        run: |
          sed -i "s|image: docker.io/khanhdev13/spring-boot-app:.*|image: docker.io/khanhdev13/spring-boot-app:${{ github.sha }}|g" k8s/backend-deployment.yaml
          sed -i "s|image: docker.io/khanhdev13/vue-app:.*|image: docker.io/khanhdev13/vue-app:${{ github.sha }}|g" k8s/frontend-deployment.yaml

      - name: Commit and Push Changes
        run: |
          git config --global user.email "hotmashmallow@gmail.com"
          git config --global user.name "giakhanh22024558"
          git add k8s/
          git commit -m "Update image tags to ${{ github.sha }}"
          git push origin dev
